# Generated by Django 5.0.1 on 2024-02-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatar.jpg'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='Makale'),
        ),
    ]
