# Generated by Django 5.0.1 on 2024-02-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_profile_picture_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='comment_profile_pictures/'),
        ),
    ]
